// Generated by gencpp from file test/adder.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_ADDER_H
#define TEST_MESSAGE_ADDER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct adder_
{
  typedef adder_<ContainerAllocator> Type;

  adder_()
    : a(0)
    , b(0)  {
    }
  adder_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef uint16_t _a_type;
  _a_type a;

   typedef uint16_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::test::adder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::adder_<ContainerAllocator> const> ConstPtr;

}; // struct adder_

typedef ::test::adder_<std::allocator<void> > adder;

typedef boost::shared_ptr< ::test::adder > adderPtr;
typedef boost::shared_ptr< ::test::adder const> adderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::adder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::adder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test::adder_<ContainerAllocator1> & lhs, const ::test::adder_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test::adder_<ContainerAllocator1> & lhs, const ::test::adder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test::adder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::adder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::adder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::adder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::adder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::adder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::adder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e689bd5e4bb85cf611fb121d2a0d923b";
  }

  static const char* value(const ::test::adder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe689bd5e4bb85cf6ULL;
  static const uint64_t static_value2 = 0x11fb121d2a0d923bULL;
};

template<class ContainerAllocator>
struct DataType< ::test::adder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/adder";
  }

  static const char* value(const ::test::adder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::adder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 a\n"
"uint16 b\n"
;
  }

  static const char* value(const ::test::adder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::adder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct adder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::adder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::adder_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_ADDER_H
